hostname = asimov-138.svail.baidu.com
dataset: ai2_arc	dataset: ai2_arc	downloads: 8032	likes: 1	
dataset: ai2_arc,ARC-Challenge	splits: train: 1119 rows, test: 1172 rows, val: 299 rows
dataset: ai2_arc,ARC-Challenge	split: train	columns: id, question, choices, answerKey
dataset: ai2_arc,ARC-Easy	splits: train: 2251 rows, test: 2376 rows, val: 570 rows
dataset: ai2_arc,ARC-Easy	split: train	columns: id, question, choices, answerKey
***ERROR***
model: None
data: H:ai2_arc
eqn: None
splits: train
split: train
task: None
error: (<class 'requests.exceptions.HTTPError'>, HTTPError('405 Client Error: Not Allowed for url: https://huggingface.co/api/models-tags-by-type'), <traceback object at 0x7f165f52d700>)
