hostname = asimov-27.svail.baidu.com
calling my_eval in eval_for_classify_tokens.py
seed: 42
label_list: [0, 1, 2, 3, 4, 5, 6, 7, 8]
interned_labels: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8}
num_labels: 9
label_to_id: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8}
load_metric: seqeval
***ERROR***	model: P:bert-base-cased	data: H:conll2003	eqn: classify_tokens: ner_tags ~ tokens	splits: test	split: test	task: None	error: (<class 'AssertionError'>, AssertionError('label mismatch: model has 2 labels, but dataset has 9 labels'), <traceback object at 0x7f22e53dbec0>)
