hostname = asimov-145.svail.baidu.com
dataset: tweets_hate_speech_detection	dataset: tweets_hate_speech_detection	downloads: 497	likes: 6	
dataset: tweets_hate_speech_detection	splits: train: 31962 rows
dataset: tweets_hate_speech_detection	split: train	columns: label, tweet
dataset: tweets_hate_speech_detection	labels: no-hate-speech, hate-speech
***ERROR***
model: None
data: H:tweets_hate_speech_detection
eqn: None
splits: train
split: train
task: None
error: (<class 'requests.exceptions.HTTPError'>, HTTPError('405 Client Error: Not Allowed for url: https://huggingface.co/api/models-tags-by-type'), <traceback object at 0x7facd178aec0>)
